### ISSUE TITLE
Please someone solve my issue... i've got this error...how to solve it all to run the dirsearch

### ISSUE THREAD

**Issue by purpleseq** [maurosoria/dirsearch#1010]
[23:50:55] Starting: 
Traceback (most recent call last):
  File "/usr/share/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/usr/share/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/share/dirsearch/lib/controller/controller.py", line 242, in __init__
    self.prepare()
  File "/usr/share/dirsearch/lib/controller/controller.py", line 588, in prepare
    self.fuzzer.start()
  File "/usr/share/dirsearch/lib/core/fuzzer.py", line 142, in start
    self.setupScanners()
  File "/usr/share/dirsearch/lib/core/fuzzer.py", line 85, in setupScanners
    self.defaultScanner = Scanner(self.requester)
  File "/usr/share/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/usr/share/dirsearch/lib/core/scanner.py", line 49, in setup
    self.invalidStatus = firstResponse.status
AttributeError: 'NoneType' object has no attribute 'status'

**Comment by shelld3v** [comment]
Hi, please update your dirsearch!
