### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by shmilylty** [maurosoria/dirsearch#1032]
### error
```
[Exception in thread Thread-29#:
Traceback (most recent call last):
  File "C:\tools\dirsearch\lib\core\fuzzer.py", line 233, in thread_proc
#    wildcard, response = self.scan(path)
#  File "C:\tools\dirsearch\lib\core\fuzzer.py", line 184, in scan
#    response = self.requester.request(path)#
  File "C:\tools\dirsearch\lib\connection\requester.py", line 296, in request
###    raise RequestException({"message": err_msg})
lib.connection.request_exception.#RequestException: {'message': None}
#
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
##        ] 64%   7071/10991        76/s       job    :1/1  self.run()
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
[  File "C:\tools\dirsearch\lib\core\fuzzer.py", line 246, in thread_proc
##    callback(path, e.args[0]["message"])
  File "C:\tools\dirsearch\lib\controller\controller.py", line 472, in append_error_log
##    #msg += NEW_LINE + " " * 4 + error_msg
TypeError: can only concatenate str (not "NoneType") to str#
```
#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Can I have the URL?

**Comment by shelld3v** [comment]
Duplicate of #1023
