### ISSUE TITLE
when i give subdomain file path its dosn't work

### ISSUE THREAD

**Issue by itsrvsingh** [maurosoria/dirsearch#1040]
python3 dirsearch.py -l alive.txt -r -w 2.txt -o dir.txt

Traceback (most recent call last):
  File "dirsearch.py", line 46, in <module>
    main = Program()
  File "dirsearch.py", line 31, in __init__
    options = Options()
  File "/home/hack3r/tools/dirsearch/lib/core/options.py", line 50, in __init__
    elif not len(self.url_list):
TypeError: object of type 'generator' has no len()

**Comment by itsrvsingh** [comment]
But how can i fix this i don't have idea

**Comment by shelld3v** [comment]
@itsrvsingh Re-install dirsearch (from github)

**Comment by itsrvsingh** [comment]
ok thanks now its working properly
