### ISSUE TITLE
AttributeError: 'Requester' object has no attribute 'scheme'

### ISSUE THREAD

**Issue by GiuBravo** [maurosoria/dirsearch#1044]
Traceback (most recent call last):
  File "dirsearch.py", line 46, in <module>
    main = Program()
  File "dirsearch.py", line 42, in __init__
    Controller(options, output)
  File "/root/opt/dirsearch/lib/controller/controller.py", line 86, in __init__
    self.run()
  File "/root/opt/dirsearch/lib/controller/controller.py", line 177, in run
    self.requester = Requester(
  File "/root/opt/dirsearch/lib/connection/requester.py", line 78, in __init__
    raise RequestException("Unsupported URI scheme: {0}".format(self.scheme))
AttributeError: 'Requester' object has no attribute 'scheme'

**Comment by GiuBravo** [comment]
Command:

```python3 dirsearch.py -l urls -f -b -t 100 -e php,jsp,pdf,txt -x 300-599 -r```

This seems to be when using ```-l urls``` instead ```-u http://URL```

**Comment by shelld3v** [comment]
No it's because one of your URLs inside the file has an invalid URI scheme (`invalid://website.com`)
