### ISSUE TITLE
python3 dirsearch.py Import error

### ISSUE THREAD

**Issue by puskal1** [maurosoria/dirsearch#110]
Traceback (most recent call last):
  File "dirsearch.py", line 25, in <module>
    from lib.core import ArgumentParser
  File "/root/dirsearch/lib/core/__init__.py", line 1, in <module>
    from .Dictionary import *
  File "/root/dirsearch/lib/core/Dictionary.py", line 20, in <module>
    import urllib.request, urllib.parse, urllib.error
  File "/usr/lib/python3.6/urllib/request.py", line 84, in <module>
    import base64
  File "/usr/lib/python3.6/base64.py", line 10, in <module>
    import struct
  File "/usr/lib/python3.6/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'

**Comment by puskal1** [comment]
Solved 
alias python="/usr/bin/python3.6"
