### ISSUE TITLE
Error using python 3.10 on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by yhojann-cl** [maurosoria/dirsearch#1103]
When run application:

```
$ ./dirsearch.py -u https://.../ -e php
Traceback (most recent call last):
  File "/.../dirsearch/thirdparty/oset/pyoset.py", line 9, in <module>
    from collections import MutableSet
ImportError: cannot import name 'MutableSet' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../dirsearch/./dirsearch.py", line 26, in <module>
    from lib.core import ArgumentParser
  File "/.../dirsearch/lib/core/__init__.py", line 1, in <module>
    from .ArgumentParser import *
  File "/.../dirsearch/lib/core/ArgumentParser.py", line 24, in <module>
    from thirdparty.oset import *
  File "/.../dirsearch/thirdparty/oset/__init__.py", line 3, in <module>
    from .pyoset import oset
  File "/.../dirsearch/thirdparty/oset/pyoset.py", line 12, in <module>
    from ._abc import MutableSet
  File "/.../dirsearch/thirdparty/oset/_abc.py", line 12, in <module>
    raise ImportError("Use native ABC classes istead of this one.")
ImportError: Use native ABC classes istead of this one.
```

In Python 3.9 `collections` is `collections.abc`.

**Comment by shelld3v** [comment]
Please re-install your dirsearch for the lastest version

**Comment by shelld3v** [comment]
Old bug, closing rn
