### ISSUE TITLE
Just Dont Know What happend 

### ISSUE THREAD

**Issue by YutakaTan** [maurosoria/dirsearch#1106]
C:\Users\76892\Desktop\mytool\dirsearch-master>python dirsearch.py -u lib.blcu.edu.cn -s 3

Traceback (most recent call last):
  File "C:\Users\76892\Desktop\mytool\dirsearch-master\dirsearch.py", line 67, in <module>
    main()
  File "C:\Users\76892\Desktop\mytool\dirsearch-master\dirsearch.py", line 63, in main
    Controller(options, output)
  File "C:\Users\76892\Desktop\mytool\dirsearch-master\lib\controller\controller.py", line 50, in __init__
    self._import(options.session_file)
  File "C:\Users\76892\Desktop\mytool\dirsearch-master\lib\controller\controller.py", line 59, in _import
    with open(session_file, "rb") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '3'

**Comment by shelld3v** [comment]
Command-line flag for request delay his now only `--delay`, `-s` is for another thing. Use `-h` to view all flags
