### ISSUE TITLE
'utf-8' codec can't decode byte 0xe5 in position 33: invalid continuation byte

### ISSUE THREAD

**Issue by ad0nis** [maurosoria/dirsearch#1115]
### What is the current behavior?

dirsearch from kali repos on kali 2022.1 crashed due to issue with decoding a byte in the server's response.

Traceback (most recent call last):
  File "/home/kali/.local/bin/dirsearch", line 8, in <module>
    sys.exit(Program())
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/controller/controller.py", line 241, in __init__
    self.prepare()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/controller/controller.py", line 578, in prepare
    self.fuzzer.start()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/fuzzer.py", line 147, in start
    self.setup_scanners()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/fuzzer.py", line 88, in setup_scanners
    self.default_scanner = Scanner(self.requester)
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/scanner.py", line 120, in setup
    if first_path in first_response.body.decode():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 33: invalid continuation byte

What actually happens?

dirsearch crashes

### What is the expected behavior?

dirsearch finishes execution at some point

What it should be instead?

Dirsearch should catch the server's response and attempt to decode it, and if an invalid response is received, it should be logged instead of crashing the scanner.

### Any additional information?

dirsearch from kali repos on kali 2022.1 crashed due to issue with decoding a byte in the server's response.

Traceback (most recent call last):
  File "/home/kali/.local/bin/dirsearch", line 8, in <module>
    sys.exit(Program())
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/controller/controller.py", line 241, in __init__
    self.prepare()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/controller/controller.py", line 578, in prepare
    self.fuzzer.start()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/fuzzer.py", line 147, in start
    self.setup_scanners()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/fuzzer.py", line 88, in setup_scanners
    self.default_scanner = Scanner(self.requester)
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/home/kali/.local/lib/python3.9/site-packages/dirsearch/lib/core/scanner.py", line 120, in setup
    if first_path in first_response.body.decode():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 33: invalid continuation byte

#### Checker:
 - [ ] I tested in the latest version of dirsearch
 (Sorry - I didn't re-test from a git pull)

**Comment by shelld3v** [comment]
Hi, installing via Kali repo is most likely deprecated, please use git to install for the latest updates of the tool

**Comment by OmarJAhmad** [comment]
> Hi, installing via Kali repo is most likely deprecated, please use git to install for the latest updates of the tool

thanks m8
