### ISSUE TITLE
ConnectionResetError(10054, '远 程主机强迫关闭了一个现有的连接。', None, 10054, None))"):1/1  Thread-21

### ISSUE THREAD

**Issue by zhibx** [maurosoria/dirsearch#1142]
### What is the current behavior?

您好！
我在使用中遇到这个错误，请问这是什么原因造成的呢？盼望您的回复！
```
Traceback (most recent call last):
[  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
#    wildcard, response = self.scan(path)
#  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
    response = self._requester.request(path)#
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\connection\requester.py", line 258, in request
#    raise RequestException(simple_err_msg, err_msg)
#lib.core.exceptions.               ] 28%   4488/15550       181/s       RequestExceptionException in thread job: ('There was a problem in the request to: http://test.com/', "('Connection aborted.', ConnectionResetError(10054, '远 程主机强迫关闭了一个现有的连接。', None, 10054, None))"):1/1  Thread-21
errors
During handling of the above exception, another exception occurred:

:2109Traceback (most recent call last):
:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
    self.run()
wildcard, response = self.scan(path)  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run

  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
    self._target(*self._args, **self._kwargs)
response = self._requester.request(path)  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 230, in thread_proc

  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\connection\requester.py", line 258, in request
        callback(path, e.args[1])raise RequestException(simple_err_msg, err_msg)

lib.core.exceptions.  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\controller\controller.py", line 478, in error_callback
RequestException:     raise SkipTargetInterrupt("Too many request errors")
('There was a problem in the request to: http://test.com/', "('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))")
lib.core.exceptions.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
SkipTargetInterrupt:   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
Too many request errors
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 230, in thread_proc
    callback(path, e.args[1])
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\controller\controller.py", line 478, in error_callback
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
[######              ] 30%   4735/15550       152/s       job:1/1  errors:2352Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
Exception in thread Thread-2:
    Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
wildcard, response = self.scan(path)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
    wildcard, response = self.scan(path)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
response = self._requester.request(path)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\connection\requester.py", line 258, in request
    response = self._requester.request(path)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\connection\requester.py", line 258, in request
    raise RequestException(simple_err_msg, err_msg)    raise RequestException(simple_err_msg, err_msg)
Exception in thread
lib.core.exceptionslib.core.exceptions..RequestExceptionRequestException: : ('There was a problem in the request to: http://test.com/', "('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))")
('There was a problem in the request to: http://test.com/', "('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))")
Thread-16
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
        wildcard, response = self.scan(path)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
    self.run()self.run()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    response = self._requester.request(path)  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 230, in thread_proc


  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 230, in thread_proc
      File "C:\Users\Administrator\Desktop\dirsearch-master\lib\connection\requester.py", line 258, in request
    callback(path, e.args[1])raise RequestException(simple_err_msg, err_msg)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\controller\controller.py", line 478, in error_callback
    Exception in thread callback(path, e.args[1])
lib.core.exceptionsThread-17
:
raise SkipTargetInterrupt("Too many request errors")  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\controller\controller.py", line 478, in error_callback

lib.core.exceptionsTraceback (most recent call last):
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 213, in thread_proc
..RequestExceptionSkipTargetInterrupt:     Too many request errors
    raise SkipTargetInterrupt("Too many request errors")wildcard, response = self.scan(path)
lib.core.exceptions
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\fuzzer.py", line 169, in scan
.: SkipTargetInterruptException in thread ('There was a problem in the request to: http://test.com/', "('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))")
Thread-13:
:
During handling of the above exception, another exception occurred:
```

### Any additional information?
win server2019  
python3.8.8

#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
错误信息搞砸了。您可以尝试使用 `-q` 重新运行命令吗？

**Comment by zhibx** [comment]
Please check the attachment.


[__22-07-29_08-52-20.txt](https://github.com/maurosoria/dirsearch/files/9215121/__22-07-29_08-52-20.txt)

**Comment by shelld3v** [comment]
It's a server issue, we can do nothing. Though I will fix it to clean the error in the output

**Comment by shelld3v** [comment]
I have confirmed that you are using an old version. Closing as per

**Comment by zhibx** [comment]
Thank you for all your assistance. I have tested in the new version and the same bug still occurs occasionally. I think it may be caused by my server.

**Comment by shelld3v** [comment]
It was caused by your server but did the error message got messed up like in the previous version? Or was it a clean short message?

**Comment by zhibx** [comment]
yes,the error message got messed up like in the previous version

**Comment by shelld3v** [comment]
@zhibx Can you give me the error output you got, as well as the output of `./dirsearch.py --version`?

**Comment by zhibx** [comment]
C:\Users\Administrator\Desktop\dirsearch-master>python dirsearch.py --version
dirsearch v0.4.2.7
[error.txt](https://github.com/maurosoria/dirsearch/files/9219259/error.txt)

**Comment by zhibx** [comment]
he got new error when i run dirsearch

```
C:\Users\Administrator\Desktop\dirsearch-master>python dirsearch.py
Traceback (most recent call last):
  File "dirsearch.py", line 68, in <module>
    main()
  File "dirsearch.py", line 53, in main
    options = options()
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\core\options.py", line 49, in options
    opt.urls = uniq(opt.urls)
  File "C:\Users\Administrator\Desktop\dirsearch-master\lib\utils\common.py", line 33, in uniq
    return type_(filter(None, dict.fromkeys(array)))
TypeError: 'NoneType' object is not iterable

C:\Users\Administrator\Desktop\dirsearch-master>
```

**Comment by shelld3v** [comment]
@zhibx it's because you didn't select the target, I have made a PR to recover the old error message too

**Comment by zhibx** [comment]
received with thanks.
