### ISSUE TITLE
`NoneType` object is not iterable

### ISSUE THREAD

**Issue by its0x08** [maurosoria/dirsearch#1144]
### What is the current behavior?

There is a `TypeError`.

What actually happens?

It doesn't run. It exits because of the error.

### What is the expected behavior?
To not exit and show the usage message instead.

OS, python version, screenshots, dirsearch command, console output, ...?
```python
~# dirsearch 
Traceback (most recent call last):
  File "/usr/bin/dirsearch", line 68, in <module>
    main()
  File "/usr/bin/dirsearch", line 53, in main
    options = options()
  File "/scripts/dirsearch/lib/core/options.py", line 49, in options
    opt.urls = uniq(opt.urls)
  File "/scripts/dirsearch/lib/utils/common.py", line 33, in uniq
    return type_(filter(None, dict.fromkeys(array)))
TypeError: 'NoneType' object is not iterable
~# 
```
#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by its0x08** [comment]
I bypassed (temporary fixed) it by replacing  this
```python 
def uniq(array, type_=list):
    return type_(filter(None, dict.fromkeys(array)))
```` 
with 
```python
def uniq(array, type_=list):
    return array
````

**Comment by its0x08** [comment]
Never mind! **The fix I proposed doesn't work!!**
It was showing the above error if no argument is supplied to the command.
So I rolled back my local changes and its working fine except for that one error if nothing is supplied..
