### ISSUE TITLE
Unexpected SSL error

### ISSUE THREAD

**Issue by Tsunamori** [maurosoria/dirsearch#1168]
### What is the current behavior?

Hi I'll just paste my command and response here. Feel free to test around the target for more info I assume it should be fine.
```
sudo python3 dirsearch.py -u https://hermes.pingan.com/   

  _|. _ _  _  _  _ _|_    v0.4.2.8                                     
 (_||| _) (/_(_|| (_| )                                                
                                                                       
Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 25
Wordlist size: 11374

Output File: /home/####/dirsearch/reports/https_hermes.pingan.com/__22-08-07_21-29-32.txt

Target: https://hermes.pingan.com/

[21:29:32] Starting:                                                   

Unexpected SSL error
```

### What is the expected behavior?

After some searching around I think it should auto connect the host to bypass the SSL err?

### Any additional information?

working on kali, python3.9.2, and the dirsearch is up to date.

#### Checker:
 - [yes] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Run `python3 dirsearch.py ... --log log.log` and check `log.log`

**Comment by shelld3v** [comment]
I ran it successfully:

```
$ python3 dirsearch.py -u https://hermes.pingan.com/ --log log.log

  _|. _ _  _  _  _ _|_    v0.4.2.8
 (_||| _) (/_(_|| (_| )

Extensions: php | HTTP method: GET | Threads: 5 | Wordlist size: 9380

Output File: /tmp/dirsearch/reports/https_hermes.pingan.com/__22-08-08_10-51-55.txt

Log File: /tmp/dirsearch/log.log

Target: https://hermes.pingan.com/

[10:51:55] Starting:
...
```

**Comment by Tsunamori** [comment]
Thanks for the quick response!
I got the log print - with the SSL error - and checked into it.
The first several lines are like this:
```
2022-08-08 04:09:12,987 [ERROR] HTTPSConnectionPool(host='hermes.pingan.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1129)
```
I haven't got a clear clue about how to fix it safely and completely, but it looks like the problem is not from the dirsearch code.
Here's my temporary solution for anyone who got same error there: **echo "CipherString=DEFAULT@SECLEVEL=1" >> /etc/ssl/openssl.cnf** (and turn it back to CipherString=DEFAULT@SECLEVEL=2 after scan, cuz the prior lowering the security level for SSL connection)
[the solution ref here](https://stackoverflow.com/questions/61626206/what-could-cause-dh-key-too-small-error)
Cheers!
