### ISSUE TITLE
error when url not working

### ISSUE THREAD

**Issue by hasanimad** [maurosoria/dirsearch#1201]
dirsearch version 0.4.2.

when encountering a non-working url, it gives this error

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 83, in __init__
    self.ip = socket.gethostbyname(self.host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 48, in <module>
    main = Program()
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/lib/python3/dist-packages/dirsearch/lib/controller/controller.py", line 217, in __init__
    self.requester = Requester(
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 87, in __init__
    self.ip = socket.gethostbyname(self.host, None, socket.AF_INET6)
TypeError: gethostbyname() takes exactly 1 argument (3 given)`

**Comment by Prady18** [comment]
[]()~~ustha full install ing~~

**Comment by Prady18** [comment]
What happened

**Comment by shelld3v** [comment]
It's an old bug, it will be fixed once dirsearch v0.4.3 is released on PyPi, sorry for the inconvenience!
