### ISSUE TITLE
error in run dirsearch

### ISSUE THREAD

**Issue by netwons** [maurosoria/dirsearch#1224]
**code**:python3 dirsearch.py -u https://securemail.bbb.com/help/ -w ~/ffuf/SecLists/Discovery/Web-Content/raft-large-directories.txt
```
Traceback (most recent call last):
Exception in thread Thread-16:
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
Traceback (most recent call last):
Exception in thread Thread-108:
    self.scan(self._base_path + path, scanners)
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    response = self._requester.request(path)
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    self.scan(self._base_path + path, scanners)
    raise RequestException(err_msg)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    response = self._requester.request(path)
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    raise RequestException(err_msg)
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

    self.run()
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    self.run()
    callback(e)
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    raise SkipTargetInterrupt("Too many request errors")
    self._target(*self._args, **self._kwargs)
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-184:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Exception in thread Thread-61:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    callback(e)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-67:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-50:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-123:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-174:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
Exception in thread Thread-74:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-173:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-73:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
Exception in thread Thread-175:
    self.scan(self._base_path + path, scanners)
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    self.scan(self._base_path + path, scanners)
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

    raise RequestException(err_msg)
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    response = self._requester.request(path)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    raise RequestException(err_msg)
  File "/usr/lib/python3.8/threading.py", line 870, in run
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
    callback(e)
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    raise SkipTargetInterrupt("Too many request errors")
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
    callback(e)
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-192:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-46:
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    response = self._requester.request(path)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
    self.run()
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com
  File "/usr/lib/python3.8/threading.py", line 870, in run

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
    self.run()
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
  File "/usr/lib/python3.8/threading.py", line 870, in run
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-188:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-91:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 261, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 168, in scan
    response = self._requester.request(path)
  File "/home/netwons/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: Cannot connect to: securemail.earlywarning.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/netwons/dirsearch/lib/core/fuzzer.py", line 268, in thread_proc
    callback(e)
  File "/home/netwons/dirsearch/lib/controller/controller.py", line 482, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors

```

**Comment by shelld3v** [comment]
`./dirsearch.py --version` output?

**Comment by netwons** [comment]
@shelld3v 
dirsearch v0.4.3

**Comment by shelld3v** [comment]
It was not an issue from dirsearch but the server refused your connections, probably because of the massive number of requests, try lowering the threads. Though dirsearch should have handled those tracebacks, so I will keep this open

**Comment by skor21** [comment]
I am having problems as well. dirsearch v0.4.3. any help would be great.

Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] Y
Installing required dependencies...
Traceback (most recent call last):
  File "/home/skor/toolkit/dirsearch/dirsearch.py", line 73, in <module>
    main()
  File "/home/skor/toolkit/dirsearch/dirsearch.py", line 66, in main
    from lib.controller.controller import Controller
  File "/home/skor/toolkit/dirsearch/lib/controller/controller.py", line 64, in <module>
    from lib.reports.sqlite_report import SQLiteReport
  File "/home/skor/toolkit/dirsearch/lib/reports/sqlite_report.py", line 19, in <module>
    import sqlite3
  File "/usr/local/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by chanseo** [comment]
what is the problem i didnt get it, can u help

python3 dirsearch.py -u uu.nl -e php
Traceback (most recent call last):
  File "/home/rambo/dirsearch/dirsearch.py", line 73, in <module>
    main()
  File "/home/rambo/dirsearch/dirsearch.py", line 66, in main
    from lib.controller.controller import Controller
  File "/home/rambo/dirsearch/lib/controller/controller.py", line 64, in <module>
    from lib.reports.sqlite_report import SQLiteReport
  File "/home/rambo/dirsearch/lib/reports/sqlite_report.py", line 19, in <module>
    import sqlite3
  File "/usr/local/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by ducducuc111** [comment]
I was fix the issue '_sqlite3' in here:
https://unix.stackexchange.com/questions/610875/modulenotfounderror-no-module-named-sqlite3

**Comment by maurosoria** [comment]
Do we close this @shelld3v ?

**Comment by shelld3v** [comment]
@maurosoria this was never a bug from the start, just the error wasn't handled probably. I think I will just close this
