### ISSUE TITLE
AttributeError: module 'spnego' has no attribute 'ContextProxy'

### ISSUE THREAD

**Issue by SherlockLee592** [maurosoria/dirsearch#1285]
Traceback (most recent call last):
  File "dirsearch.py", line 73, in <module>
    main()
  File "dirsearch.py", line 66, in main
    from lib.controller.controller import Controller
  File "C:\Users\xxx\Desktop\dirsearch\lib\controller\controller.py", line 29, in <module>
    from lib.connection.requester import Requester
  File "C:\Users\xxx\Desktop\dirsearch\lib\connection\requester.py", line 30, in <module>
    from requests_ntlm import HttpNtlmAuth
  File "C:\python3\lib\site-packages\requests_ntlm\__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "C:\python3\lib\site-packages\requests_ntlm\requests_ntlm.py", line 14, in <module>
    class ShimSessionSecurity:
  File "C:\python3\lib\site-packages\requests_ntlm\requests_ntlm.py", line 17, in ShimSessionSecurity
    def __init__(self, context: spnego.ContextProxy) -> None:
AttributeError: module 'spnego' has no attribute 'ContextProxy'

how to solve this problem？？？

**Comment by SherlockLee592** [comment]
python3.7.4

**Comment by shelld3v** [comment]
I can't figure out what happened here, but maybe you should try to re-install `requests-ntlm` and `pyspnego` modules? I'm not sure if it will fix the issue but I can't find your problem on the internet or anywhere else

**Comment by psawa** [comment]
Same issue here

**Comment by Prady18** [comment]
The error message you provided indicates that there is an issue with the spnego module used by the requests_ntlm module. Here are some steps you can try to solve the problem:

1.Upgrade the spnego module:
In your terminal or command prompt, run the following command: pip install --upgrade spnego. This will upgrade the spnego module to the latest version.

2.Reinstall the requests_ntlm module:
In your terminal or command prompt, run the following command: pip uninstall requests-ntlm to uninstall the requests_ntlm module. Then, run pip install requests-ntlm to reinstall it.

3.Check if other modules are causing conflicts:
It's possible that other modules you have installed are causing conflicts with spnego. You can try uninstalling any other modules that you think might be causing the problem and see if that helps.

4.Check your Python version:
The spnego module may require a specific version of Python. Make sure you are using a compatible version by running python --version in your terminal or command prompt.

**If none of these steps solve the problem, you may need to seek further assistance from the developers of the spnego or requests_ntlm modules**. Ok buddy 😸

**try this if you face any problem even after trying this then let me know**

**Comment by psawa** [comment]
I solved the problem by downgrading requests_ntlm to 1.1.0
