### ISSUE TITLE
未知的错误

### ISSUE THREAD

**Issue by websecer** [maurosoria/dirsearch#1308]
```
$ python dirsearch.py -u http://xxxxxxxxxxxxxxxxxxxxxxxxxx
E:\Myprofile\Soft\Penetration_test\dirsearch\dirsearch.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, VersionConflict
Traceback (most recent call last):
  File "E:\Myprofile\Soft\Penetration_test\dirsearch\dirsearch.py", line 73, in <module>
    main()
  File "E:\Myprofile\Soft\Penetration_test\dirsearch\dirsearch.py", line 66, in main
    from lib.controller.controller import Controller
  File "E:\Myprofile\Soft\Penetration_test\dirsearch\lib\controller\controller.py", line 21, in <module>
    import psycopg
  File "D:\Python310\lib\site-packages\psycopg\__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
  File "D:\Python310\lib\site-packages\psycopg\pq\__init__.py", line 16, in <module>
    from . import abc
  File "D:\Python310\lib\site-packages\psycopg\pq\abc.py", line 9, in <module>
    from typing_extensions import TypeAlias
  File "D:\Python310\lib\site-packages\typing_extensions.py", line 3011, in <module>
    def get_protocol_members(__tp: type) -> typing.FrozenSet[str]:
  File "D:\Python310\lib\typing.py", line 298, in inner
    return cached(*args, **kwds)
  File "D:\Python310\lib\typing.py", line 1079, in __getitem__
    return self.copy_with(params)
  File "D:\Python310\lib\typing.py", line 1082, in copy_with
    return _GenericAlias(self.__origin__, params,
  File "D:\Python310\lib\typing.py", line 972, in __init__
    self.__parameters__ = _collect_type_vars(params, typevar_types=_typevar_types)
  File "D:\Python310\lib\site-packages\typing_extensions.py", line 197, in _collect_type_vars
    if _should_collect_from_parameters(t):
  File "D:\Python310\lib\site-packages\typing_extensions.py", line 171, in _should_collect_from_parameters
    t, (typing._GenericAlias, _types.GenericAlias, _types.UnionType)
AttributeError: module 'types' has no attribute 'UnionType'. Did you mean: 'FunctionType'?

```

**Comment by shelld3v** [comment]
You should report it to `psycopg`
