### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by b1gdog** [maurosoria/dirsearch#1312]
扫描HTTPS URL时报错
Traceback (most recent call last):
  File "dirsearch.py", line 73, in <module>
    main()
  File "dirsearch.py", line 66, in main
    from lib.controller.controller import Controller
  File "/root/dirsearch/lib/controller/controller.py", line 29, in <module>
    from lib.connection.requester import Requester
  File "/root/dirsearch/lib/connection/requester.py", line 23, in <module>
    import requests
  File "/root/Python-3.8.0/lib/python3.8/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/root/Python-3.8.0/lib/python3.8/site-packages/urllib3/__init__.py", line 41, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168

[root@xxx dirsearch]# python3 -V
Python 3.8.0
[root@xxx dirsearch]# pip3 -V
pip 23.2.1 from /root/Python-3.8.0/lib/python3.8/site-packages/pip (python 3.8)

**Comment by Prady18** [comment]
@cukw update this tool once

**Comment by Prady18** [comment]
@cukw And if it is not happening even after updating, then unistall it once and install it again because this problem also happened to me a few days back.
