### ISSUE TITLE
Disable Exceptions in output?

### ISSUE THREAD

**Issue by iseries** [maurosoria/dirsearch#1365]
### Is it possible to disable exceptions in the CLI Output?

I want to get rid of this:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/core/fuzzer.py", line 246, in thread_proc
    callback(e)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/controller/controller.py", line 497, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors
Exception in thread Thread-3283 (thread_proc):
Traceback (most recent call last):
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/core/fuzzer.py", line 239, in thread_proc
    self.scan(self._base_path + path, scanners)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/core/fuzzer.py", line 155, in scan
    response = self._requester.request(path)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/connection/requester.py", line 222, in request
    raise RequestException(err_msg)
lib.core.exceptions.RequestException: There was a problem in the request to: https://SOME_DOMAIN.de/index.php.bak

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/core/fuzzer.py", line 246, in thread_proc
    callback(e)
  File "/media/veracrypt1/Home/hTools/dirsearch/lib/controller/controller.py", line 497, in raise_error
    raise SkipTargetInterrupt("Too many request errors")
lib.core.exceptions.SkipTargetInterrupt: Too many request errors

```

**Comment by nrathaus** [comment]
You can modify the `settings.py` file to say:
`MAX_CONSECUTIVE_REQUEST_ERRORS = some_large_number`

To prevent the rising of this exception

**Comment by shelld3v** [comment]
I expected the error to be handled in an user-friendly style, seems like a bug to me
