### ISSUE TITLE
bug!???

### ISSUE THREAD

**Issue by 687766616e** [maurosoria/dirsearch#179]
```
$ python3 dirsearch.py --random-agents -e php,asp,aspx,jsp,ashx,do,sql,pl,py,cgi,htm,html,xhtml -u "http://2.1.test.com.us/admin/"
...
403 -    1KB - /admin/.htusers
24.96% - Last request to: admin_newspost.phpException in thread Thread-1:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/dirsearch/lib/core/Fuzzer.py", line 142, in thread_proc
    status, response = self.scan(path)
  File "/data/data/com.termux/files/home/dirsearch/lib/core/Fuzzer.py", line 117, in scan
    response = self.requester.request(path)
  File "/data/data/com.termux/files/home/dirsearch/lib/connection/Requester.py", line 158, in request
    timeout=self.timeout
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 482, in get
    return self.request('GET', url, **kwargs)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 420, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/data/data/com.termux/files/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/dirsearch/lib/core/Fuzzer.py", line 142, in thread_proc
    status, response = self.scan(path)
  File "/data/data/com.termux/files/home/dirsearch/lib/core/Fuzzer.py", line 117, in scan
    response = self.requester.request(path)
  File "/data/data/com.termux/files/home/dirsearch/lib/connection/Requester.py", line 158, in request
    timeout=self.timeout
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 482, in get
    return self.request('GET', url, **kwargs)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/data/data/com.termux/files/home/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 420, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/data/data/com.termux/files/usr/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/data/data/com.termux/files/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

403 -    1KB - /admin/cgi.pl/
...
Task Completed
$
```

**Comment by maurosoria** [comment]
Mmm this is a connection problem in the scanning. Maybe a WAF or something?

**Comment by adibikar** [comment]
Me too,
`9.30% - Errors: 26 - Last request to:`

**Comment by shelld3v** [comment]
This is the server problem, not dirsearch!

**Comment by shelld3v** [comment]
Please close this
