### ISSUE TITLE
ModuleNotFoundError: No module named 'zlib'

### ISSUE THREAD

**Issue by lordokeson** [maurosoria/dirsearch#184]
When i tried to launch Dirsearch.py for the first time after installation i got this error

root@kali:~/Desktop/tools/dirsearch# ./dirsearch.py
Traceback (most recent call last):
  File "./dirsearch.py", line 26, in <module>
    from lib.core import ArgumentParser
  File "/root/Desktop/tools/dirsearch/lib/core/init.py", line 3, in <module>
    from .Fuzzer import *
  File "/root/Desktop/tools/dirsearch/lib/core/Fuzzer.py", line 21, in <module>
    from lib.connection.RequestException import RequestException
  File "/root/Desktop/tools/dirsearch/lib/connection/init.py", line 2, in <module>
    from .Requester import *
  File "/root/Desktop/tools/dirsearch/lib/connection/Requester.py", line 28, in <module>
    import thirdparty.requests as requests
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/init.py", line 58, in <module>
    from . import utils
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/packages/init.py", line 3, in <module>
    from . import urllib3
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/packages/urllib3/init.py", line 10, in <module>
    from .connectionpool import (
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/root/Desktop/tools/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 5, in <module>
    import zlib
ModuleNotFoundError: No module named 'zlib'

i ryed to launch Dirsearch.py and i got this error

**Comment by mzfr** [comment]
@lordokeson Which python version were you using?
