### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by Bo0oM** [maurosoria/dirsearch#22]
```
[10:50:52] 301 -    0B  - /admin2/index.php  ->  https://bo0om.ru/admin2/
[10:51:04] 301 -    0B  - /admin_area/index.php  ->  https://bo0om.ru/admin_area/
22.89% - Last request to: admin_setup.phpException in thread Thread-4:
Traceback (most recent call last):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 397, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 151, in thread_proc
    status, response = self.scan(path)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 110, in scan
    response = self.requester.request(path)
  File "/home/bo0om/soft/dirsearch/lib/connection/Requester.py", line 108, in request
    response = requests.get(url, proxies=proxy, verify=False, allow_redirects=self.redirect, headers=headers, timeout=self.timeout)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 447, in read_chunked
    self._update_chunk_length()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 401, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

[10:51:43] 301 -    0B  - /adminarea/index.php  ->  https://bo0om.ru/adminarea/
```

**Comment by maurosoria** [comment]
Thank you for reporting this.

I've created a separated branch to attend this issue. I'd be grateful if you test it, because it's not easy to reproduce.

the branch is issue22

Thanks in advance

**Comment by Bo0oM** [comment]
For reproduce:
`./dirsearch.py -w dirsearch.txt -e php -u https://bo0om.ru`

https://github.com/Bo0oM/fuzz.txt/blob/master/dirsearch.txt


exceptions:
```
[10:12:32] 200 -   79B  - /test.html
92.42% - Last request to: test2.htmlException in thread Thread-6:
Traceback (most recent call last):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 397, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 151, in thread_proc
    status, response = self.scan(path)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 110, in scan
    response = self.requester.request(path)
  File "/home/bo0om/soft/dirsearch/lib/connection/Requester.py", line 108, in request
    response = requests.get(url, proxies=proxy, verify=False, allow_redirects=self.redirect, headers=headers, timeout=self.timeout)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 447, in read_chunked
    self._update_chunk_length()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 401, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 397, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 151, in thread_proc
    status, response = self.scan(path)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 110, in scan
    response = self.requester.request(path)
  File "/home/bo0om/soft/dirsearch/lib/connection/Requester.py", line 108, in request
    response = requests.get(url, proxies=proxy, verify=False, allow_redirects=self.redirect, headers=headers, timeout=self.timeout)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 447, in read_chunked
    self._update_chunk_length()
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 401, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

[10:12:39] 403 -  353B  - /text-base/etc/passwd
[10:12:44] 301 -  228B  - /tmp  ->  http://bo0om.ru/tmp/
[10:12:44] 200 -  162B  - /tmp/
[10:12:49] 301 -    0B  - /tmp/index.php  ->  https://bo0om.ru/tmp/
93.96% - Last request to: topicException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 151, in thread_proc
    status, response = self.scan(path)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 110, in scan
    response = self.requester.request(path)
  File "/home/bo0om/soft/dirsearch/lib/connection/Requester.py", line 108, in request
    response = requests.get(url, proxies=proxy, verify=False, allow_redirects=self.redirect, headers=headers, timeout=self.timeout)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 572, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 646, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
thirdparty.requests.exceptions.InvalidSchema: No connection adapters were found for 'Trace.axd::$DATA'

[10:13:05] 301 -  231B  - /upload  ->  http://bo0om.ru/upload/
[10:13:06] 200 -  632B  - /upload/
97.27% - Last request to: web.config.bakException in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 151, in thread_proc
    status, response = self.scan(path)
  File "/home/bo0om/soft/dirsearch/lib/core/Fuzzer.py", line 110, in scan
    response = self.requester.request(path)
  File "/home/bo0om/soft/dirsearch/lib/connection/Requester.py", line 108, in request
    response = requests.get(url, proxies=proxy, verify=False, allow_redirects=self.redirect, headers=headers, timeout=self.timeout)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 572, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/bo0om/soft/dirsearch/thirdparty/requests/sessions.py", line 646, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
thirdparty.requests.exceptions.InvalidSchema: No connection adapters were found for 'web.config::$DATA'
```

**Comment by maurosoria** [comment]
This still happening?
