### ISSUE TITLE
decode() argument 'encoding' must be str, not None

### ISSUE THREAD

**Issue by moein9** [maurosoria/dirsearch#267]
hello devteam
**before everything thanks for this amazing tool.**

i was using this settings and i got this error

python3 dirsearch.py -u https://example.com/ -e * -r -R 5 -f -x 401,403,404,301,302,303,400

[17:15:34] Starting: 
[17:17:22] 200 -  404B  - /.well-known/openid-configuration                                    
[17:17:22] 200 -  404B  - /.well-known/openid-configuration/
[17:19:40] 200 -   33B  - /download/                                                                                           
[17:19:53] 200 -   15KB - /favicon.ico                                                
[17:23:11] Starting: .well-known/openid-configuration/                                                                         
[17:30:18] Starting: download/                                                                                                 
[17:31:28] 200 -  570B  - /download/%2e%2e/google.com                                          
[17:31:28] 200 -  570B  - /download/%2e%2e/google.com.CHANGELOG.md
[17:31:28] 200 -  570B  - /download/%2e%2e/google.com/
[17:33:47] 200 -    3KB - /download/debug/pprof/goroutine?debug=1.CHANGELOG.md                                                 
[17:33:47] 200 -    9KB - /download/debug/pprof/goroutine?debug=1
[17:33:47] 200 -    3KB - /download/debug/pprof/goroutine?debug=1/
[17:33:47] 200 -   14KB - /download/debug/pprof/heap     
[17:33:49] 200 -   33KB - /download/debug/pprof/trace      
[17:37:27] Starting: download/%2e%2e//google.com/                                                                                                           
[17:46:02] Starting: download/debug/pprof/goroutine?debug=1/  
`Traceback (most recent call last):
  File "dirsearch.py", line 46, in <module>
    main = Program()
  File "dirsearch.py", line 42, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/kali/Desktop/dirsearch/lib/controller/Controller.py", line 205, in __init__
    self.wait()
  File "/home/kali/Desktop/dirsearch/lib/controller/Controller.py", line 535, in wait
    self.fuzzer.start()
  File "/home/kali/Desktop/dirsearch/lib/core/Fuzzer.py", line 102, in start
    self.setupScanners()
  File "/home/kali/Desktop/dirsearch/lib/core/Fuzzer.py", line 70, in setupScanners
    self.scanners["dotfiles"] = Scanner(self.requester, self.testFailPath, preffix=".")
  File "/home/kali/Desktop/dirsearch/lib/core/Scanner.py", line 46, in __init__
    self.setup()
  File "/home/kali/Desktop/dirsearch/lib/core/Scanner.py", line 71, in setup
    self.dynamicParser = DynamicContentParser(
  File "/home/kali/Desktop/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 16, in __init__
    self.generateDynamicMarks(firstPage, secondPage)
  File "/home/kali/Desktop/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 33, in generateDynamicMarks
    self.cleanPage = self.removeDynamicContent(firstPage, self.dynamicMarks)
  File "/home/kali/Desktop/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 107, in removeDynamicContent
    page = page.decode(encoding, errors="replace")
TypeError: decode() argument 'encoding' must be str, not None`

**Comment by shelld3v** [comment]
Hi, I am trying to find the root cause of this bug, but I can't see any problem in our code. So can you try again with the latest version of dirsearch? Thank you!
