### ISSUE TITLE
Exception in thread 

### ISSUE THREAD

**Issue by nesi10062** [maurosoria/dirsearch#354]
someone help please!!
`root@kali:~/dirsearch# python3 dirsearch.py -u http://10.10.10.28 -e php

 _|. _ _  _  _  _ _|_    v0.3.9
(_||| _) (/_(_|| (_| )

Extensions: php | HTTP method: GET | Threads: 12 | Wordlist size: 6564

Error Log: /root/dirsearch/logs/errors-20-09-13_10-57-59.log

Target: http://10.10.10.28

Output File: /root/dirsearch/reports/10.10.10.28/20-09-13_10-57-59

[10:57:59] Starting: 
7.69% - Last request to: .hsenvException in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

11.06% - Last request to: .pep8Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

45.90% - Last request to: culeadora.txtException in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

53.38% - Last request to: footerException in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

57.45% - Last request to: images_adminException in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

60.68% - Last request to: joomla/administratorException in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 164, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 441, in matchCallback
    excludeRegex = re.compile(excludeRegexp)
UnboundLocalError: local variable 'excludeRegexp' referenced before assignment

Task Completed
`

**Comment by shelld3v** [comment]
Sorry so much @nesi10062! I have created a PR to fix the bug, but waiting for the author to merge it. Please wait a little bit!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by nesi10062** [comment]
Thank you so much @shelld3v for the fast response, I've tried to delete and download the file again and its worked!!

**Comment by shelld3v** [comment]
You can close it now ❤️
