### ISSUE TITLE
NameError: 'GetConsoleScreenBufferInfo' is not defined (Cygwin)

### ISSUE THREAD

**Issue by davidhcefx** [maurosoria/dirsearch#375]
Platform (`uname -a`): `CYGWIN_NT-10.0 Win 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin`
Python: `Python 3.6.10`

I got `NameError: name 'GetConsoleScreenBufferInfo' is not defined` when trying to run `dirsearch` for any url I have tried.

```
[23:14:23] Starting:
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined



Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined


Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined


Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/dirsearch/lib/core/Fuzzer.py", line 169, in thread_proc
    callback(result)
  File "/opt/dirsearch/lib/controller/Controller.py", line 473, in notFoundCallback
    self.output.lastPath(path, self.index, len(self.dictionary))
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 158, in lastPath
    self.inLine(message)
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 46, in inLine
    self.erase()
  File "/opt/dirsearch/lib/output/CLIOutput.py", line 53, in erase
    csbi = GetConsoleScreenBufferInfo()
NameError: name 'GetConsoleScreenBufferInfo' is not defined
```

**Comment by shelld3v** [comment]
Hi, let me take a look!

**Comment by shelld3v** [comment]
Hello @davidhcefx, can I ask that have you ever get the same error in the older version of dirsearch

**Comment by davidhcefx** [comment]
@shelld3v I didn't get the same error in a pretty old version (2020/1/4).
After some more investigation, I found that when importing `thirdparty/colorama/win32`, it fell into the `exception` clause on line 15, which prevented it from executing the `else` clause, in which the function `GetConsoleScreenBufferInfo` has been defined.

**Comment by shelld3v** [comment]
Hi, for your information, that is not actually the root cause if you look closely at the filename. It's looked like dirsearch should recognize your machine as an Unix system and should not import `thirdparty.colorama.win32`

**Comment by shelld3v** [comment]
Hi, I think I have fixed everything, can you recheck?

**Comment by davidhcefx** [comment]
@shelld3v Yes, the newest code fixed the issue.

**Comment by shelld3v** [comment]
Thanks for the ping, you can close this now
