### ISSUE TITLE
Dirsearch tool gets terminated becaue of error

### ISSUE THREAD

**Issue by 0xdekster** [maurosoria/dirsearch#407]
Hi

I am continuously getting this error when i run dirsearch on a list of targets.
It just terminates here

100.00% - Last request to: ~rpcuserTraceback (most recent call last):
  File "./dirsearch.py", line 46, in <module>
    main = Program()
  File "./dirsearch.py", line 42, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/deksterecon/dirsearch/lib/controller/Controller.py", line 151, in __init__
    self.output.target(self.currentUrl)
TypeError: 'str' object is not callable

Any help is appreciated

**Comment by shelld3v** [comment]
Hi, let me take a look

**Comment by 0xdekster** [comment]
yes please @shelld3v

**Comment by 0xdekster** [comment]
@shelld3v 

Running it like this

cd dirsearch && python3 ./dirsearch.py --url-list=/subdomains.txt -e php,html,js,jar -t 40 --timeout=20 -x 301,302,401,503,407,402,400,403,404,500,405,407,429,406,504,503,502,403,308 --plain-text-report=dirsearch.txt;

**Comment by shelld3v** [comment]
Thanks, @0xdekster! I have found the root cause of the bug and working on it to patch all the buggy codes and then merge the fix. Please wait a little bit!

**Comment by 0xdekster** [comment]
@shelld3v  sure i am waiting for it.

**Comment by 0xdekster** [comment]
@shelld3v Is the issue fixed ? How can i grab the latest ?

**Comment by shelld3v** [comment]
No, it hasn't been fixed yet!

**Comment by 0xdekster** [comment]
@maurosoria  @shelld3v Not fixed yet , getting errors 

Traceback (most recent call last):
  File "./dirsearch.py", line 46, in <module>
    main = Program()
  File "./dirsearch.py", line 35, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/deksterecon/dirsearch/lib/core/ArgumentParser.py", line 30, in __init__
    self.parseConfig()
  File "/deksterecon/dirsearch/lib/core/ArgumentParser.py", line 328, in parseConfig
    self.excludeSubdirs = config.safe_get("general", "exclude-subdirs", None)
  File "/deksterecon/dirsearch/lib/utils/DefaultConfigParser.py", line 28, in safe_get
    result = configparser.ConfigParser.get(self, section, option)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%ff/

**Comment by shelld3v** [comment]
We just fixed it a few hours ago, can you recheck?

**Comment by 0xdekster** [comment]
@shelld3v  yes working now

**Comment by shelld3v** [comment]
👍
