### ISSUE TITLE
Getting configparser syntax error

### ISSUE THREAD

**Issue by ColdFusionX** [maurosoria/dirsearch#415]
Just pulled the latest update and now am unable to execute the program, getting the following error:

```shell
cfx:  /opt/dirsearch  |master ✓|
→ ./dirsearch.py
Traceback (most recent call last):
  File "./dirsearch.py", line 46, in <module>
    main = Program()
  File "./dirsearch.py", line 35, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/opt/dirsearch/lib/core/ArgumentParser.py", line 30, in __init__
    self.parseConfig()
  File "/opt/dirsearch/lib/core/ArgumentParser.py", line 328, in parseConfig
    self.excludeSubdirs = config.safe_get("general", "exclude-subdirs", None)
  File "/opt/dirsearch/lib/utils/DefaultConfigParser.py", line 28, in safe_get
    result = configparser.ConfigParser.get(self, section, option)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%ff/'
```

**Comment by tibug** [comment]
![image](https://user-images.githubusercontent.com/68282195/93718966-de774c00-fb7f-11ea-8b0e-5c1f3616f6dd.png)
Nope ???

**Comment by nghiaclv-10397** [comment]
I got the same error !
`Traceback (most recent call last):
  File "./dirsearch.py", line 46, in <module>
    main = Program()
  File "./dirsearch.py", line 35, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/home/kgcg/dirsearch/lib/core/ArgumentParser.py", line 30, in __init__
    self.parseConfig()
  File "/home/kgcg/dirsearch/lib/core/ArgumentParser.py", line 328, in parseConfig
    self.excludeSubdirs = config.safe_get("general", "exclude-subdirs", None)
  File "/home/kgcg/dirsearch/lib/utils/DefaultConfigParser.py", line 28, in safe_get
    result = configparser.ConfigParser.get(self, section, option)
  File "/usr/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%ff/'
`

**Comment by mimi-sec** [comment]
Limited in my experience with python, but the %ff is in the default.conf, temp fix is to comment out the exclude-subdirs line or add another % in front of the %ff (it would appear that configparser doesn't like single %.)

**Comment by ColdFusionX** [comment]
Adding an extra `%` on exclude-subdirs line in default.conf definitely mitigates the issue but then we have to forcefully use `-r` flag to make dirsearch work.
I am not sure if its intended for users to use `-r` on every command, I have used dirsearch alot previously and never was forced to use `-r` flag forcefully.

**Comment by shelld3v** [comment]
Hi, sorry all, I am working on a fix!

**Comment by ColdFusionX** [comment]
Thanks @shelld3v @maurosoria latest commit resolves the issue :+1:
