### ISSUE TITLE
[WINDOWS] cant parsing and saving to log while complex URL is included.

### ISSUE THREAD

**Issue by madjapahit** [maurosoria/dirsearch#50]
trying with complex URL to bruteforce app function :

http://sub.sub.sub.domain.net/func/service.dll?fid=415&f=/myfunc/loginverify&checkif=

---------------------------------------------------------------------------------------------

And for traceback :

Error Log: C:\Users\murray\Downloads\dirsearch-master\dirsearch-master\logs\errors-17-01-17_16-16-37.log

Target: http://sub.sub.sub.domain.net/func/service.dll?fid=415&f=/myfunc/loginverify&checkif=

Traceback (most recent call last):
  File "dirsearch.py", line 40, in <module>
    main = Program()
  File "dirsearch.py", line 34, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\murray\Downloads\dirsearch-master\dirsearch-master\lib\controller\Controller.py", line 123, in __init__
    self.setupReports(self.requester)
  File "C:\Users\murray\Downloads\dirsearch-master\dirsearch-master\lib\controller\Controller.py", line 232, in setupReports
    outputFile)
  File "C:\Users\murray\Downloads\dirsearch-master\dirsearch-master\lib\reports\BaseReport.py", line 32, in __init__
    self.open()
  File "C:\Users\murray\Downloads\dirsearch-master\dirsearch-master\lib\reports\BaseReport.py", line 43, in open
    self.file = open(self.output, 'w+')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\murray\\Downloads\\dirsearch-master\\dirsearch-master\\reports\\sub.sub.sub.domain.net\\func/service._17-01-17_16-16-38'

**Comment by SUHAR1K** [comment]
I has the same problem. I added folders by myself.

**Comment by maurosoria** [comment]
I merged SUHAR1K patch

madjapahit, can you check if the problem persist?
