### ISSUE TITLE
default.conf configparser.DuplicateOptionError:

### ISSUE THREAD

**Issue by MichaelShoemaker** [maurosoria/dirsearch#537]
### dirsearch.py throws a configparser.DuplicateOptionError</br>

This is the code I was trying to run for TryHackMe
`python3 dirsearch.py -u http://10.10.128.226 -e php,html -x 400,401,403`
The Error is below:
```
Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/opt/dirsearch/lib/core/argument_parser.py", line 30, in __init__
    self.parseConfig()
  File "/opt/dirsearch/lib/core/argument_parser.py", line 343, in parseConfig
    config.read(configPath)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/opt/dirsearch/default.conf' [line  9]: option 'follow-redirects' in section 'general' already exists

```

### Any additional information?

Simply by removing default.conf the script executes fine now. 
I am running Python 3.8.5

**Comment by MichaelShoemaker** [comment]
This issue was fixed with #536
