### ISSUE TITLE
Problem dealing with bad certificates event by turning -b flag

### ISSUE THREAD

**Issue by soufianetahiri** [maurosoria/dirsearch#546]
### What is the current behavior?
Problems dealing with bad certificates event by turning -b flag

What actually happens?
1.04% - Last request to: 500Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
0.94% - Last request to: 2013    self.run()
1.06% - Last request to: 2009  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/dirsearch/lib/core/Fuzzer.py", line 142, in thread_proc
1.22% - Last request to: 12    status, response = self.scan(path)
[15:17:21] 301 -    0B  - /404  ->  https://REDACTED.com/404/index.html
  File "/usr/share/dirsearch/lib/core/Fuzzer.py", line 117, in scan
    response = self.requester.request(path)
  File "/usr/share/dirsearch/lib/connection/Requester.py", line 152, in request
1.73% - Last request to: 30    response = self.session.get(
  File "/usr/share/dirsearch/thirdparty/requests/sessions.py", line 482, in get
1.81% - Last request to: _img    return self.request('GET', url, **kwargs)
  File "/usr/share/dirsearch/thirdparty/requests/sessions.py", line 470, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/dirsearch/thirdparty/requests/sessions.py", line 610, in send
    r.content
  File "/usr/share/dirsearch/thirdparty/requests/models.py", line 734, in content
2.41% - Last request to: _js    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/share/dirsearch/thirdparty/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/share/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/share/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/share/dirsearch/thirdparty/requests/packages/urllib3/response.py", line 411, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/usr/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
2.16% - Last request to: 6    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
2.18% - Last request to: _notesssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)

### What is the expected behavior?
No verbosity 
What it should be instead?
Handling correctly the exceptions.
### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?
![image](https://user-images.githubusercontent.com/17729335/97996366-f16c7580-1de7-11eb-87db-d3f619430b93.png)

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by shelld3v** [comment]
Were you able to visit the webpage from your browser?

**Comment by soufianetahiri** [comment]
Yes with absolutely no problem and as you can see from the screenshot, even dirsearch was able to get some urls

**Comment by maurosoria** [comment]
Hello @soufianetahiri ,

Does the problem persist? Try using dirsearch with a proxy like BURP and tell us what happened.

Regards,
Mauro

**Comment by soufianetahiri** [comment]
I'll give it a try and get back to you

**Comment by shelld3v** [comment]
@soufianetahiri Fixed yet? From your screenshot, I can see that you are using an old version of dirsearch!

**Comment by shelld3v** [comment]
Any update?

**Comment by soufianetahiri** [comment]
Couldn't reproduce!
Thanks for keeping an eye on this !
