### ISSUE TITLE
double at the beginning of the keyword //

### ISSUE THREAD

**Issue by Phoenix1112** [maurosoria/dirsearch#547]
hello. thank you this project. When using dirsearch, there is a double // in front of results.

```
[14:55:48] 500 -  164B  - //account/login.txt
[14:55:48] 500 -  164B  - //account/login.json
[14:55:48] 500 -  164B  - //account/login.yaml
[14:55:48] 500 -  164B  - //account/login.sql
[14:55:48] 500 -  164B  - //account/login.ini
[14:55:48] 500 -  164B  - //account/login.yml
[14:55:48] 500 -  164B  - //account/login.csv
[14:55:48] 500 -  164B  - //account/login.db
[14:55:48] 500 -  164B  - //account/login.zip
[14:55:48] 500 -  164B  - //account/login.xsl
[14:55:48] 500 -  164B  - //account/login.py
[14:55:48] 500 -  164B  - //account/login.rb
[14:55:48] 500 -  164B  - //account/logon
[14:55:48] 500 -  164B  - //account/signin


```

Why does // appear at the beginning of these keywords. how can i fix this. The keywords in my word list do not begin with / or //.

**Comment by shelld3v** [comment]
Hi, sorry about this, we are fixing it (#538)

**Comment by Phoenix1112** [comment]
@shelld3v i hav this error

```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/dirsearch# python3 dirsearch.py -u https://safetyhub.paypal.com/ -e html,php -w db/dicc.txt
Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/root/dirsearch/lib/core/argument_parser.py", line 337, in __init__
    self.exit_on_error = options.exit_on_error
AttributeError: 'Values' object has no attribute 'exit_on_error'

```

**Comment by shelld3v** [comment]
Hi, sorry again for that, this will be fixed soon.

**Comment by shelld3v** [comment]
There were a lot of bugs in the past time, we are trying to find a way to stop something like that in the future. And thank you again for using our tool, if there is any suggestion for a new feature, please let us know by creating a new issue, or comment on #384!

**Comment by AlxAlindayu** [comment]
> 
> 
> Hi, sorry again for that, this will be fixed soon.

same issue 

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "D:\dirsearch\lib\core\argument_parser.py", line 337, in __init__
    self.exit_on_error = options.exit_on_error
AttributeError: 'Values' object has no attribute 'exit_on_error'


using windows 10,
python 3.8.5 version ciao !

**Comment by shelld3v** [comment]
Hi @AlxAlindayu, we are fixing it!
