### ISSUE TITLE
"Values' object has no attribute 'exit_on_error"

### ISSUE THREAD

**Issue by zebra777** [maurosoria/dirsearch#562]
### What is the current behavior?

python3 dirsearch.py -E -u http://10.10.245.239              

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/home/kali/tools/dirsearch/lib/core/argument_parser.py", line 337, in __init__
    self.exit_on_error = options.exit_on_error
AttributeError: 'Values' object has no attribute 'exit_on_error'

**Comment by zebra777** [comment]
After a few new installations it works again
