### ISSUE TITLE
[Bug] urllib3.exceptions Error

### ISSUE THREAD

**Issue by as7r0nu11** [maurosoria/dirsearch#574]
I just got this error when i run this

```
dirsearch -u https://***************/ -e asp,aspx,cgi,php,jsp,html,htm,js
```

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Tools/dirsearch/thirdparty/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dirsearch", line 47, in <module>
    main = Program()
  File "/usr/bin/dirsearch", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/user/Tools/dirsearch/lib/controller/controller.py", line 220, in __init__
    self.wait()
  File "/home/user/Tools/dirsearch/lib/controller/controller.py", line 625, in wait
    self.fuzzer.start()
  File "/home/user/Tools/dirsearch/lib/core/fuzzer.py", line 101, in start
    self.setupScanners()
  File "/home/user/Tools/dirsearch/lib/core/fuzzer.py", line 67, in setupScanners
    self.defaultScanner = Scanner(self.requester, self.testFailPath)
  File "/home/user/Tools/dirsearch/lib/core/scanner.py", line 46, in __init__
    self.setup()
  File "/home/user/Tools/dirsearch/lib/core/scanner.py", line 50, in setup
    firstResponse = self.requester.request(firstPath, nodelay=True)
  File "/home/user/Tools/dirsearch/lib/connection/requester.py", line 159, in request
    response = self.session.request(
  File "/home/user/Tools/dirsearch/thirdparty/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/Tools/dirsearch/thirdparty/requests/sessions.py", line 697, in send
    r.content
  File "/home/user/Tools/dirsearch/thirdparty/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/user/Tools/dirsearch/thirdparty/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
thirdparty.requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

```

**Comment by maurosoria** [comment]
Hello @as7r0nu11 

Does the problem persist?

**Comment by as7r0nu11** [comment]
Hi @maurosoria 
No, I did not face it any more after the updates
but faced another issue 
`[03:03:55] Starting: 
Fatal error during site scanning: Invalid URL`
that have been solved by `--request-by-hostname` flag
I suggest to suggest to the user to use this flag in the alert when it pops up as a feature 

Thank you

**Comment by shelld3v** [comment]
This should be another issue

**Comment by shelld3v** [comment]
Hi @as7r0nu11, can you close this issue now?

**Comment by sahil0012** [comment]
Hack hidden wifi help me
