### ISSUE TITLE
[bug] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 6: invalid start byte

### ISSUE THREAD

**Issue by random-robbie** [maurosoria/dirsearch#575]
### What is the current behavior?
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/dirsearch/lib/core/Fuzzer.py", line 148, in thread_proc
    callback(result)
  File "/root/dirsearch/lib/controller/Controller.py", line 342, in matchCallback
    if excludeText in path.response.body.decode():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 6: invalid start byte
```
### What is the expected behavior?

Continue to display what has been found

What it should be instead?

### Any additional information?

ubuntu 20, python3.8

**Comment by shelld3v** [comment]
Hi @random-robbie, thank you a lot for updating dirsearch wordlist! This will be fixed soon
