### ISSUE TITLE
Scan multiple sites 

### ISSUE THREAD

**Issue by getcode2git** [maurosoria/dirsearch#60]
hello，I Scan multiple sites at the same time, the  tool run error：
```python
Traceback (most recent call last):
  File "dirsearch.py", line 40, in <module>
    main = Program()
  File "dirsearch.py", line 34, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/tools/dirsearch/lib/controller/Controller.py", line 134, in __init__
    self.wait()
  File "/root/tools/dirsearch/lib/controller/Controller.py", line 330, in wait
    self.fuzzer.start()
  File "/root/tools/dirsearch/lib/core/Fuzzer.py", line 80, in start
    self.setupScanners()
  File "/root/tools/dirsearch/lib/core/Fuzzer.py", line 59, in setupScanners
    self.scanners[extension] = Scanner(self.requester, self.testFailPath, "." + extension)
  File "/root/tools/dirsearch/lib/core/Scanner.py", line 44, in __init__
    self.setup()
  File "/root/tools/dirsearch/lib/core/Scanner.py", line 48, in setup
    firstResponse = self.requester.request(firstPath)
  File "/root/tools/dirsearch/lib/connection/Requester.py", line 151, in request
    {'message': 'CONNECTION TIMEOUT: There was a problem in the request to: {0}'.format(path)}
lib.connection.RequestException.RequestException: {'message': 'CONNECTION TIMEOUT: There was a problem in the request to: qsYkJ4xZvPdh.aspx'}
```

**Comment by amocrenco** [comment]
Your internet channel is flooded with your HTTP requests / website is not responding because you DoSed it. 

But most likely it's the first issue.

Try generating less traffic.
