### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by luapy** [maurosoria/dirsearch#640]
Hi~
I got a  problem When I execute command like
`python3 dirsearch.py -l .\result.txt -w .\final.txt -t 20 --plain-text-report report.txt --random-user-agent`
I get a error like the follow picture that tell me the system can't find the specified path
![qqq3](https://user-images.githubusercontent.com/24366795/100368804-029f4f80-303f-11eb-9308-5268a1df5968.png)
And if I delete the report output path argument , everything works well

Env:python3.8 in win10

**Comment by shelld3v** [comment]
Hi, we will investigate this!

**Comment by shelld3v** [comment]
Hi, there are Chinese words so I can't know the full error message! Can you copy-paste it for me!

**Comment by luapy** [comment]
> Hi, there are Chinese words so I can't know the full error message! Can you copy-paste it for me!

FileNotFoundError: [WinError 3] system can't find the specified path.: ''

**Comment by luapy** [comment]
> Hi, there are Chinese words so I can't know the full error message! Can you copy-paste it for me!

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\fibr3\Desktop\SRC\Auto\dirsearch\lib\controller\controller.py", line 206, in __init__
    self.setupReports(self.requester)
  File "C:\Users\fibr3\Desktop\SRC\Auto\dirsearch\lib\controller\controller.py", line 455, in setupReports
    PlainTextReport(
  File "C:\Users\fibr3\Desktop\SRC\Auto\dirsearch\lib\reports\base_report.py", line 108, in __init__
    super().__init__(host, port, protocol, basePath, output, batch)
  File "C:\Users\fibr3\Desktop\SRC\Auto\dirsearch\lib\reports\base_report.py", line 52, in __init__
    self.open()
  File "C:\Users\fibr3\Desktop\SRC\Auto\dirsearch\lib\reports\base_report.py", line 76, in open
    makedirs(dirname(output), exist_ok=True)
  File "C:\Users\fibr3\AppData\Local\Programs\Python\Python38\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ''

**Comment by shelld3v** [comment]
Hi, I am finding a solution

**Comment by shelld3v** [comment]
I think that it is not important to use `--plain-text-report`, since the result will be automatically saved in the `BATCH-...` folder

**Comment by luapy** [comment]
Ok, Thanks
