### ISSUE TITLE
Getting Error when running dirsearch on a list of urls

### ISSUE THREAD

**Issue by 0xdekster** [maurosoria/dirsearch#646]
Hi 

When running dirsearch on a list of URLS ,  i am getting this below error , please check and let me know the solution.

5.83% - Job: 1/23 - Last request to: .lein-failuresException in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/deksterecon/dirsearch/lib/core/fuzzer.py", line 172, in thread_proc
    status, response = self.scan(path)
  File "/deksterecon/dirsearch/lib/core/fuzzer.py", line 144, in scan
    if self.getScannerFor(path).scan(path, response):
  File "/deksterecon/dirsearch/lib/core/scanner.py", line 116, in scan
    elif redirectToInvalid and ratio >= (self.ratio - 0.15):
NameError: name 'redirectToInvalid' is not defined

**Comment by shelld3v** [comment]
Hi, sorry, I have submitted a fix for it, waiting for being merged. You can currently try: `git clone https://github.com/shelld3v/dirsearch.git -b patch-6`

**Comment by 0xdekster** [comment]
@shelld3v  Issue is same here also 

UnboundLocalError: local variable 'redirectToInvalid' referenced before assignment
17.44% - Job: 1/23 - Last request to: Citrix/Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/deksterecon/dirsearch/lib/core/fuzzer.py", line 172, in thread_proc
    status, response = self.scan(path)
  File "/deksterecon/dirsearch/lib/core/fuzzer.py", line 144, in scan
    if self.getScannerFor(path).scan(path, response):
  File "/deksterecon/dirsearch/lib/core/scanner.py", line 118, in scan
    elif redirectToInvalid and ratio >= (self.ratio - 0.15):
UnboundLocalError: local variable 'redirectToInvalid' referenced before assignment

**Comment by shelld3v** [comment]
Hi, I updated! Can you re-git my patch and check again?

**Comment by knoxisus** [comment]
i've done it, but still getting the same error.

**Comment by shelld3v** [comment]
`git clone https://github.com/shelld3v/dirsearch.git -b patch-6`

**Comment by maurosoria** [comment]
This should be fixed now

**Comment by shelld3v** [comment]
Hi, fixed, try `git clone https://github.com/maurosoria/dirsearch.git` normally.
