### ISSUE TITLE
Problems with 429 detection

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#658]
### What is the current behavior?

Double `429 Too Many Requests detected: Server is blocking requests` messages, error: `Segmentation fault (core dumped)` after ignoring 429 status code.

### What is the expected behavior?

Nothing bad should happen!

### Any additional information?

```
$ python3 dirsearch.py -u 127.0.0.1:4444

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, asp, aspx, jsp, html, htm, js | HTTP method: GET | Threads: 20 | Wordlist size: 11793

Error Log: /tmp/dirsearch/logs/errors-20-12-09_13-52-25.log

Target: http://127.0.0.1:4444/

Output File: /tmp/dirsearch/reports/127.0.0.1/_20-12-09_13-52-25.txt

[13:52:25] Starting:
429 Too Many Requests detected: Server is blocking requests
429 Too Many Requests detected: Server is blocking requests
[e]xit / [c]ontinue / [i]gnore: i
[13:52:29] 200 -   53B  - /404.html
[13:52:38] 200 -    4KB - /index.html
97.82% - Last request to: webticket/webticketservice.svcException in thread Thread-13:
97.83% - Last request to: wheels/Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
97.85% - Errors: 1 - Last request to: wishlist.php    conn = connection.create_connection(
  File "/home/admin/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
97.87% - Errors: 5 - Last request to: wishlist.asp    raise err
Segmentation fault (core dumped)
```

#### Checker:
 - [x] I have read the documentation (README)

/cc @wdahlenburg, @maurosoria

**Comment by shelld3v** [comment]
Actually fixed with this PR: #657
