### ISSUE TITLE
Exception in thread using proxy

### ISSUE THREAD

**Issue by alfonsocaponi** [maurosoria/dirsearch#662]
# python3.6 dirsearch.py -l listfile -t 30 -q --full-url -r -R 3 -b --timeout=15 -w list.txt --proxy=1.2.3.4:8080 -s 1

...
...

Exception in thread Thread-1080:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/bb/tools/dirsearch/lib/core/fuzzer.py", line 172, in thread_proc
    status, response = self.scan(path)
  File "/bb/tools/dirsearch/lib/core/fuzzer.py", line 142, in scan
    response = self.requester.request(path)
  File "/bb/tools/dirsearch/lib/connection/requester.py", line 173, in request
    timeout=self.timeout,
  File "/bb/tools/dirsearch/thirdparty/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/bb/tools/dirsearch/thirdparty/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/bb/tools/dirsearch/thirdparty/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/bb/tools/dirsearch/thirdparty/requests/adapters.py", line 304, in get_connection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "/bb/tools/dirsearch/thirdparty/requests/utils.py", line 900, in prepend_scheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "/usr/lib/python3.6/urllib/parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib/python3.6/urllib/parse.py", line 120, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments

**Comment by shelld3v** [comment]
Hi, can you check again without the `--timeout=15` argument

**Comment by alfonsocaponi** [comment]
Hi, unfortunately it's the same :(

**Comment by shelld3v** [comment]
Hi, can you check if targets in `listfile` are valid URLs?

**Comment by shelld3v** [comment]
Hi, fixed?

**Comment by shelld3v** [comment]
Can you give us a response?
