### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by vishnurajkv** [maurosoria/dirsearch#666]
[12:59:33] Starting: phpMyAdmin1/
Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/dirsearch/lib/controller/controller.py", line 225, in __init__
    self.wait()
  File "/root/dirsearch/lib/controller/controller.py", line 663, in wait
    self.fuzzer.start()
  File "/root/dirsearch/lib/core/fuzzer.py", line 118, in start
    thread.start()
  File "/usr/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by shelld3v** [comment]
Hi, it looks like you have set the number of threads too huge, for your computer power (you should set your threads < 200)

**Comment by vishnurajkv** [comment]
I was running with 120 threads for 50K subdomains

**Comment by shelld3v** [comment]
Wow, 50K subdomains is a huge number! As a bug hunter, I advise you to find interesting subdomains to brute-force only, not all of them, except if you want to wait for years. Also, does 100 threads work without errors?

**Comment by shelld3v** [comment]
Can we close this now?

**Comment by vishnurajkv** [comment]
ok
