### ISSUE TITLE
NameError: name 'basePath' is not defined

### ISSUE THREAD

**Issue by TERADA-DANTE** [maurosoria/dirsearch#681]
### What is the current behavior?
dirsearch exposes below error.
```
Traceback (most recent call last):
  File ".\dirsearch.py", line 47, in <module>
    main = Program()
  File ".\dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\TERADA\Documents\GitHub\dirsearch\lib\controller\controller.py", line 186, in __init__
    self.requester.request("")
  File "C:\Users\TERADA\Documents\GitHub\dirsearch\lib\connection\requester.py", line 158, in request
    url = self.url + basePath + path
NameError: name 'basePath' is not defined
```
I found this issue can be solved by editing `dirsearch\lib\connection\requester.py`, line 158, as python tells.
[I requested PR to fix this issue.](https://github.com/maurosoria/dirsearch/pull/682).

### Any additional information?
My desktop enviroments 
```
Windows 10 Pro
python 3.8.4
pip 20.3.3
```
#### Checker:
 - [X] I have read the documentation (README)

**Comment by TERADA-DANTE** [comment]
This issue has been solved. #682
