### ISSUE TITLE
Gettin Error for --raw=file options - AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by kotireddyaluri** [maurosoria/dirsearch#738]
Please look into this issue, I have tried in ubuntu and mac, getting same error. Thank you.
```
ubuntu@ubuntu:~/sectools/dirsearch$ python3 dirsearch.py --raw=target_req.txt --scheme=https

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10832

Error Log: /home/koti/sectools/dirsearch/logs/errors-21-01-24_00-16-43.log

Target: https://www.example.com/

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/koti/sectools/dirsearch/lib/controller/controller.py", line 210, in __init__
    self.requester.setHeader(key, value)
  File "/home/koti/sectools/dirsearch/lib/connection/requester.py", line 127, in setHeader
    self.headers[key.strip()] = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by shelld3v** [comment]
Hi, Can I see the content inside `target_req.txt`?

**Comment by kotireddyaluri** [comment]
Thank you for the quick reply. sure, here is the target_req.txt

```
GET /adsid/google/ui HTTP/1.1
Host: adservice.google.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://www.google.com/
Connection: close
Cookie: 1P_JAR=2021-01-24-06; NID=207=YYHOcaNDW0Iulc17SIPtvX2cebRpT-QwV5Rs0bRwtcSdIMpm-zkIwnU8ljTnHfJiHPo6C_u8EtFxbX-cqwIokCwbhXBUoL6YcMzCc2fFo2c_JG8seV5XdIJqDyu5vkzsTwDVBJGnmBHTiXE_B8iI3l-6vCAJv-j3sTtbZ1g5r98; ANID=AHWqTUmEEGPUsq6CEWgFUqSiLVLqdXoO7X-dmumLTrOhaBduPwtqO8OB0mI4oXFk


```

**Comment by shelld3v** [comment]
Hi, this will be fixed soon!!

**Comment by kotireddyaluri** [comment]
Thank you @shelld3v and @maurosoria for the quick fix. it is working now.
