### ISSUE TITLE
traceback errors with dirsearch in kali

### ISSUE THREAD

**Issue by joekazama** [maurosoria/dirsearch#743]
when i try using dirsearch, it gives me these problems.
i am not sure if i messed up some python dependencies or...

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/PyEnvironments/Py3.8.4/dirsearch/lib/controller/controller.py", line 170, in __init__
    self.setupErrorLogs()
  File "/PyEnvironments/Py3.8.4/dirsearch/lib/controller/controller.py", line 336, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/PyEnvironments/Py3.8.4/dirsearch/logs/errors-21-01-28_10-13-02.log'

**Comment by shelld3v** [comment]
Hi, try running with `sudo` (root permission)

**Comment by joekazama** [comment]
i think it works now.   silly me.  thanks

**Comment by shelld3v** [comment]
You can close this now :)

**Comment by VISHAAL-KUMAR-A** [comment]
still I get error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 83, in __init__
    self.ip = socket.gethostbyname(self.host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 48, in <module>
    main = Program()
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/lib/python3/dist-packages/dirsearch/lib/controller/controller.py", line 217, in __init__
    self.requester = Requester(
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 87, in __init__
    self.ip = socket.gethostbyname(self.host, None, socket.AF_INET6)
TypeError: gethostbyname() takes exactly 1 argument (3 given)

**Comment by shelld3v** [comment]
@VISHAAL-KUMAR-A Please install dirsearch via git, instead of apt
