### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by direwolf314** [maurosoria/dirsearch#77]
Error since the latest pull:
[06:07:59] Starting: 
Traceback (most recent call last):
  File "/root/tools/dirsearch/dirsearch.py", line 38, in <module>
    main = Program()
  File "/root/tools/dirsearch/dirsearch.py", line 34, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/tools/dirsearch/lib/controller/Controller.py", line 135, in __init__
    self.wait()
  File "/root/tools/dirsearch/lib/controller/Controller.py", line 334, in wait
    self.fuzzer.start()
  File "/root/tools/dirsearch/lib/core/Fuzzer.py", line 80, in start
    self.setupScanners()
  File "/root/tools/dirsearch/lib/core/Fuzzer.py", line 56, in setupScanners
    self.defaultScanner = Scanner(self.requester, self.testFailPath, "")
  File "/root/tools/dirsearch/lib/core/Scanner.py", line 44, in __init__
    self.setup()
  File "/root/tools/dirsearch/lib/core/Scanner.py", line 61, in setup
    self.dynamicParser = DynamicContentParser(self.requester, firstPath, firstResponse.body, secondResponse.body)
  File "/root/tools/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 14, in __init__
    self.generateDynamicMarks(firstPage, secondPage)
  File "/root/tools/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 31, in generateDynamicMarks
    self.cleanPage = self.removeDynamicContent(firstPage, self.dynamicMarks)
  File "/root/tools/dirsearch/thirdparty/sqlmap/DynamicContentParser.py", line 101, in removeDynamicContent
    page = re.sub(r'(?s){0}.+{1}'.format(re.escape(prefix), re.escape(suffix)), "{0}{1}".format(prefix.replace('\\', r'\\'), suffix.replace('\\', r'\\')), page)
TypeError: a bytes-like object is required, not 'str'

**Comment by direwolf314** [comment]
Actually, seems to only be an issue with Jenkins servers... strange.
