### ISSUE TITLE
--request-by-hostname bug

### ISSUE THREAD

**Issue by alfonsocaponi** [maurosoria/dirsearch#794]
I tested in the latest version of dirsearch with "--request-by-hostname" options:

**# python3.6 /dirsearch/dirsearch.py --url-list=list.txt -b**

Traceback (most recent call last):
  File "/dirsearch/dirsearch.py", line 47, in <module>
    main = Program()
  File "/dirsearch/dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/dirsearch/lib/controller/controller.py", line 249, in __init__
    self.prepare()
  File "/dirsearch/lib/controller/controller.py", line 698, in prepare
    self.fuzzer.start()
  File "/dirsearch/lib/core/fuzzer.py", line 140, in start
    self.setupScanners()
  File "/dirsearch/lib/core/fuzzer.py", line 83, in setupScanners
    self.defaultScanner = Scanner(self.requester)
  File "/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/dirsearch/lib/core/scanner.py", line 63, in setup
    firstResponse.redirect, secondResponse.redirect
**TypeError: generateRedirectRegExp() missing 2 required positional arguments: 'secondLoc' and 'secondPath'**

**Comment by alfonsocaponi** [comment]
--proxy option with the same problem? :(

**Comment by shelld3v** [comment]
Hi, this is a bug and will be fixed after my PR gets merged. Now, you can only brute-force URLs that do not redirect you

**Comment by barrett092** [comment]
Yeah I get the same issue
