### ISSUE TITLE
dirsearch 0.4.1 latest git pull crash

### ISSUE THREAD

**Issue by gprime31** [maurosoria/dirsearch#795]
[23:17:03] Starting:
Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/opt/tools/dirsearch/lib/controller/controller.py", line 249, in __init__
    self.prepare()
  File "/opt/tools/dirsearch/lib/controller/controller.py", line 698, in prepare
    self.fuzzer.start()
  File "/opt/tools/dirsearch/lib/core/fuzzer.py", line 140, in start
    self.setupScanners()
  File "/opt/tools/dirsearch/lib/core/fuzzer.py", line 83, in setupScanners
    self.defaultScanner = Scanner(self.requester)
  File "/opt/tools/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/opt/tools/dirsearch/lib/core/scanner.py", line 63, in setup
    firstResponse.redirect, secondResponse.redirect
TypeError: generateRedirectRegExp() missing 2 required positional arguments: 'secondLoc' and 'secondPath'

python3 dirsearch.py -w /wordlists/short.txt -u http://example.com

**Comment by shelld3v** [comment]
Duplicate of #792

**Comment by shelld3v** [comment]
Please close this

**Comment by gprime31** [comment]
Not going to fix?
