### ISSUE TITLE
--cookie options is not work

### ISSUE THREAD

**Issue by Jack-ban** [maurosoria/dirsearch#829]
### What is the current behavior?

I just want to use --cookie options

What actually happens?

baidu.com is example site.

```bash
C:\Users\***\Desktop\tools\dirsearch>python dirsearch.py -u https://baidu.com --cookie "ffdddsdsdsd=qwe"

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10877

Output File: C:\Users\****\Desktop\tools\dirsearch\reports\baidu.com\_21-05-11_16-03-45.txt

Error Log: C:\Users\****\Desktop\tools\dirsearch\logs\errors-21-05-11_16-03-45.log

Target: https://baidu.com/

There was a problem in the request to: https://baidu.com:443/
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\tools\dirsearch\lib\controller\controller.py", line 208, in __init__
    self.requester.request("")
  File "C:\Users\****\Desktop\tools\dirsearch\lib\connection\requester.py", line 241, in request
    raise RequestException({"message": error})
lib.connection.request_exception.RequestException: {'message': 'There was a problem in the request to: https://baidu.com:443/'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\Desktop\tools\dirsearch\lib\controller\controller.py", line 214, in __init__
    raise SkipTargetInterrupt
lib.controller.controller.SkipTargetInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\Desktop\tools\dirsearch\dirsearch.py", line 47, in <module>
    main = Program()
  File "C:\Users\****\Desktop\tools\dirsearch\dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\*****\Desktop\tools\dirsearch\lib\controller\controller.py", line 254, in __init__
    self.report.completed = True
AttributeError: 'Controller' object has no attribute 'report'
```

### What is the expected behavior?

error

What it should be instead?

### Any additional information?
```bash
OS 名称:          Microsoft Windows 10 教育版
OS 版本:          10.0.14393 暂缺 Build 14393
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free
python verison: Python 3.9.1
```
OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [ ] I tested in the latest version of dirsearch 0.4.1

**Comment by shelld3v** [comment]
How did you install dirsearch? Via ZIP file or git?

**Comment by shelld3v** [comment]
We started working on this

**Comment by shelld3v** [comment]
Hi @Jack-ban, can you approve #831?
