### ISSUE TITLE
AttributeError exception when import 'ntlm_auth' on thirdparty

### ISSUE THREAD

**Issue by VitorOriel** [maurosoria/dirsearch#863]
### What is the current behavior?

When I tries to open the help menu, an exception is thrown.

### What is the expected behavior?

Opens the help menu.

### Any additional information?

* OS: Ubuntu 18.04.5 LTS
* Python version: 3.6.9
* screenshots:
![image](https://user-images.githubusercontent.com/43549176/119676118-fe989280-be13-11eb-8fde-8e5201208202.png)
* dirsearch command: `./dirsearch.py -h`
* console output:
```
Traceback (most recent call last):
  File "dirsearch.py", line 27, in <module>
    from lib.core import ArgumentParser
  File "/home/wixmix/dirsearch/lib/core/__init__.py", line 3, in <module>
    from .fuzzer import *  # noqa: F401
  File "/home/wixmix/dirsearch/lib/core/fuzzer.py", line 22, in <module>
    from lib.connection.request_exception import RequestException
  File "/home/wixmix/dirsearch/lib/connection/__init__.py", line 2, in <module>
    from .requester import *  # noqa: F401
  File "/home/wixmix/dirsearch/lib/connection/requester.py", line 28, in <module>
    from thirdparty.requests_ntlm import HttpNtlmAuth
  File "/home/wixmix/dirsearch/thirdparty/requests_ntlm/__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "/home/wixmix/dirsearch/thirdparty/requests_ntlm/requests_ntlm.py", line 11, in <module>
    from thirdparty.ntlm_auth import ntlm
  File "/home/wixmix/dirsearch/thirdparty/ntlm_auth/__init__.py", line 4, in <module>
    from . import ntlm, session_security
  File "/home/wixmix/dirsearch/thirdparty/ntlm_auth/ntlm.py", line 9, in <module>
    from thirdparty.ntlm_auth.messages import AuthenticateMessage, ChallengeMessage, \
  File "/home/wixmix/dirsearch/thirdparty/ntlm_auth/messages.py", line 9, in <module>
    from thirdparty.ntlm_auth.compute_response import ComputeResponse
  File "/home/wixmix/dirsearch/thirdparty/ntlm_auth/compute_response.py", line 12, in <module>
    import thirdparty.ntlm_auth.compute_hash as comphash
AttributeError: module 'thirdparty' has no attribute 'ntlm_auth'
```
* This problem doesn't occur when I run from the [last dirsearch release](https://github.com/maurosoria/dirsearch/releases/tag/v0.4.0).

#### Checker:
 - [X] I tested in the latest version of dirsearch (from github clone)

**Comment by shelld3v** [comment]
Hi, please upgrade your python to version 3.7 or greater

**Comment by VitorOriel** [comment]
Thanks for the quickly answer!
