### ISSUE TITLE
Error when using cookie flag

### ISSUE THREAD

**Issue by antoniosanchezc** [maurosoria/dirsearch#9]
Not sure this is caused by using the cookie flag, but it is when it happened to crash, this is the error I got:

Traceback (most recent call last):
  File "dirs3arch.py", line 36, in <module>
    main = Program()
  File "dirs3arch.py", line 32, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/Desktop/dirs3arch/lib/controller/Controller.py", line 59, in __init__
    self.wait()
  File "/root/Desktop/dirs3arch/lib/controller/Controller.py", line 199, in wait
    self.fuzzer.start()
  File "/root/Desktop/dirs3arch/lib/core/Fuzzer.py", line 75, in start
    self.testersSetup()
  File "/root/Desktop/dirs3arch/lib/core/Fuzzer.py", line 56, in testersSetup
    self.testers[extension] = NotFoundTester(self.requester, '{0}.{1}'.format(self.testFailPath, extension))
  File "/root/Desktop/dirs3arch/lib/core/NotFoundTester.py", line 34, in __init__
    self.tester = ContentTester(self.getNotFoundDynamicContentParser())
  File "/root/Desktop/dirs3arch/lib/core/NotFoundTester.py", line 41, in getNotFoundDynamicContentParser
    return DynamicContentParser(self.requester, self.notFoundPath)
  File "/root/Desktop/dirs3arch/thirdparty/sqlmap/DynamicContentParser.py", line 23, in __init__
    self.generateDynamicMarks(firstPage, secondPage)
  File "/root/Desktop/dirs3arch/thirdparty/sqlmap/DynamicContentParser.py", line 37, in generateDynamicMarks
    self.dynamicMarks += findDynamicContent(firstPage, secondPage)
NameError: global name 'findDynamicContent' is not defined

**Comment by maurosoria** [comment]
apparently it's a bug, could you provide more info? I need to reproduce the error.

**Comment by maurosoria** [comment]
Is the problem solved?

**Comment by maurosoria** [comment]
fixed
