### ISSUE TITLE
A lot of errors appear when scanning massively.

### ISSUE THREAD

**Issue by shuraros2334** [maurosoria/dirsearch#922]
When I specify a dirsearch command like this: dirsearch -e ext -l example.txt, 
then on host 3-4 I get the following errors: 

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\controller\controller.py", line 241, in __init__
    self.prepare()
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\controller\controller.py", line 583, in prepare
    self.fuzzer.start()
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\core\fuzzer.py", line 147, in start
    self.setup_scanners()
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\core\fuzzer.py", line 88, in setup_scanners
    self.default_scanner = Scanner(self.requester)
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\core\scanner.py", line 42, in __init__
    self.setup()
  File "C:\Users\Taskino\Desktop\python\dirsearch-master-new\lib\core\scanner.py", line 67, in setup
    if self.response.status == 404:
AttributeError: 'NoneType' object has no attribute 'status'

In fact, this is only one of the errors that I still have, but they all have the same ending:  'NoneType' object has no attribute 'status'

In the old version, this problem was not observed, but after reinstalling I lost it ((

#### Checker:
 - [ ] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi @shuraros2334, are you sure you are using the latest version?

**Comment by shelld3v** [comment]
What do you mean? I want to ask about your dirsearch version, the latest is v0.4.2

**Comment by shelld3v** [comment]
> I am using the latest version, I just wondered if the matter is in python

How did you confirm it? Please try this: `dirsearch --version`

**Comment by shelld3v** [comment]
If it's possible, can you give me the target?

**Comment by shuraros2334** [comment]
python dirsearch.py --v
dirsearch v0.4.2

**Comment by shuraros2334** [comment]
New error:

Traceback (most recent call last):
  File "C:\Users\Taskino\Desktop\python\dirsearch-master\dirsearch.py", line 48, in <module>
    main = Program()
  File "C:\Users\Taskino\Desktop\python\dirsearch-master\dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\Taskino\Desktop\python\dirsearch-master\lib\controller\controller.py", line 286, in __init__
    self.report.completed = True
AttributeError: 'NoneType' object has no attribute 'completed'

**Comment by shelld3v** [comment]
Hi, thanks for reporting, I will try to fix this asap

**Comment by shelld3v** [comment]
Hi, can you find any host that causes the first issue that you can give me? I want to do some tests before merging, thank you!

**Comment by shelld3v** [comment]
Hi, can you validate the fix? Thanks!

**Comment by shelld3v** [comment]
Closing first, feel free to ask for re-opening if the bugs still exist
