### ISSUE TITLE
Cannot use it

### ISSUE THREAD

**Issue by DanielAbsi** [maurosoria/dirsearch#961]
After Installing the git on a linux I'm unable to run the project. I install the file and also the requirements file. 
When I try to run the code this is what I get: 

```
Traceback (most recent call last):
  File "dirsearch.py", line 28, in <module>
    from lib.controller.controller import Controller
  File "/home/danielabsicool/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .controller import Controller  # noqa: F401
  File "/home/danielabsicool/dirsearch/lib/controller/controller.py", line 29, in <module>
    from lib.connection.requester import Requester
  File "/home/danielabsicool/dirsearch/lib/connection/requester.py", line 30, in <module>
    from thirdparty.requests_ntlm import HttpNtlmAuth
  File "/home/danielabsicool/dirsearch/thirdparty/requests_ntlm/__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "/home/danielabsicool/dirsearch/thirdparty/requests_ntlm/requests_ntlm.py", line 5, in <module>
    from cryptography import x509
ModuleNotFoundError: No module named 'cryptography'
```

How could I fix it?

**Comment by shelld3v** [comment]
@DanielAbsi are you using python 2? If not, can you try `pip install -r requirements.txt`?

**Comment by DanielAbsi** [comment]
I'm on python 3

**Comment by shelld3v** [comment]
> can you try `pip install -r requirements.txt`?
