### ISSUE TITLE
can't create a folder under reports path on windows system

### ISSUE THREAD

**Issue by newcodor** [maurosoria/dirsearch#962]
python version: Python 3.7.6
os : windows server 2016     

Because the ":" symbol in the url is invalid in the windows folder naming, the tool cannot create a folder under the reports path.

`Traceback (most recent call last):
  File "C:\tools\dirsearch\dirsearch.py", line 47, in <module>
    main = Program()
  File "C:\tools\dirsearch\dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\tools\dirsearch\lib\controller\controller.py", line 168, in __init__
    self.setup_reports()
  File "C:\tools\dirsearch\lib\controller\controller.py", line 347, in setup_reports
    FileUtils.create_directory(directory_path)
  File "C:\tools\dirsearch\lib\utils\file_utils.py", line 130, in create_directory
    os.makedirs(directory)
  File "C:\Program Files\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] Invalid directory name。: 'C:\\tools\\dirsearch\\reports\\192.168.7.5:8012`

**Comment by shelld3v** [comment]
Can you check if the issue exists in the latest commit of dirsearch? (you will have to install with git)

**Comment by newcodor** [comment]
> Can you check if the issue exists in the latest commit of dirsearch? (you will have to install with git)

This issue is indeed fixed in the latest version.

**Comment by newcodor** [comment]
This issue appeared in version 0.4.2-beta1, and was fixed in the latest version.
