### ISSUE TITLE
Crashes when name or service not known.

### ISSUE THREAD

**Issue by Xitro01** [maurosoria/dirsearch#972]
### What is the current behavior?

When I scan a list of URL's and one of the URL's does not work/respond, it will crash dirsearch:
```
Traceback (most recent call last):
  File "/home/kali/Tools/dirsearch/lib/connection/requester.py", line 83, in __init__
    self.ip = socket.gethostbyname(self.host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Tools/dirsearch/dirsearch.py", line 48, in <module>
    main = Program()
  File "/home/kali/Tools/dirsearch/dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/kali/Tools/dirsearch/lib/controller/controller.py", line 217, in __init__
    self.requester = Requester(
  File "/home/kali/Tools/dirsearch/lib/connection/requester.py", line 87, in __init__
    self.ip = socket.gethostbyname(self.host, None, socket.AF_INET6)
TypeError: gethostbyname() takes exactly 1 argument (3 given)
```

### What is the expected behavior?
It should simply skip the not working URL.

### Any additional information?
Running on: Kali Linux 2021.1 with dirsearch v0.4.2.

**Comment by shelld3v** [comment]
Thank you for reporting, this will be fixed soon

**Comment by Xitro01** [comment]
> Thank you for reporting, this will be fixed soon

I manually edited the commit that you made and this fixed the issue for me!
