### ISSUE TITLE
Bug Report - 'utf-8' codec can't decode byte 0xa4 in position 1: invalid start byte` - Windows

### ISSUE THREAD

**Issue by B4RD4k** [maurosoria/dirsearch#994]
Hi, 
I have started the dirsearch engine on some target and the response was the following:

`[09:35:58] Starting:
Traceback (most recent call last):
  File "C:\Users\noname\Desktop\Tools\dirsearch\dirsearch.py", line 48, in <module>
    main = Program()
  File "C:\Users\noname\Desktop\Tools\dirsearch\dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\controller\controller.py", line 280, in __init__
    self.prepare()
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\controller\controller.py", line 600, in prepare
    self.fuzzer.start()
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\core\fuzzer.py", line 146, in start
    self.setup_scanners()
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\core\fuzzer.py", line 88, in setup_scanners
    self.default_scanner = Scanner(self.requester)
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\core\scanner.py", line 41, in __init__
    self.setup()
  File "C:\Users\noname\Desktop\Tools\dirsearch\lib\core\scanner.py", line 119, in setup
    if first_path in first_response.body.decode(encoding_type):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 1: invalid start byte`

Can it please be recovered?

thanks

**Comment by shelld3v** [comment]
Thanks, I have submitted the PR, the issue will be fixed soon 👍
